"""JuPedSim-format sqlite trajectory writer.

Writes the v2 schema from jupedsim/sqlite_serialization.py — the Web-Based
JuPedSim viewer's upload path (backend/routes/simulation.py) accepts v1/v2
only; pnt-sim is single-floor so v3's `levels`/`landings`/`level` column
buy nothing. Standalone — no jupedsim runtime dependency, takes plain
(frame, agent_id, x, y, ori_x, ori_y) tuples.
"""

from __future__ import annotations

import sqlite3
from pathlib import Path
from typing import Iterable

DATABASE_VERSION = 2


class TrajectoryWriter:
    """Write Penn & Turner trajectories into a JuPedSim-compatible sqlite.

    Usage:
        with TrajectoryWriter(out_path, geometry_wkt, fps=10.0) as w:
            for frame in range(num_frames):
                w.write_frame(frame, [(agent_id, x, y, ori_x, ori_y), ...])
    """

    def __init__(
        self,
        output_file: Path,
        geometry_wkt: str,
        *,
        fps: float,
        commit_every_nth_frame: int = 100,
    ) -> None:
        self._output_file = Path(output_file)
        self._geometry_wkt = geometry_wkt
        self._geometry_hash = hash(geometry_wkt)
        self._fps = fps
        self._commit_every = max(1, commit_every_nth_frame)
        self._buffered = 0
        self._xmin = float("inf")
        self._xmax = float("-inf")
        self._ymin = float("inf")
        self._ymax = float("-inf")
        self._con: sqlite3.Connection | None = None

    def __enter__(self) -> "TrajectoryWriter":
        self.open()
        return self

    def __exit__(self, exc_type, exc, tb) -> None:
        self.close()

    def open(self) -> None:
        self._con = sqlite3.connect(self._output_file)
        # Same pragmas jupedsim uses — speed over crash safety; the file
        # is regenerated by re-running the sim, so durability isn't a concern.
        self._con.execute("PRAGMA synchronous=OFF;")
        self._con.execute("PRAGMA journal_mode=OFF;")
        self._create_schema()
        self._seed_geometry_and_levels()

    def write_frame(
        self,
        frame: int,
        agents: Iterable[tuple[int, float, float, float, float]],
    ) -> None:
        """Append one frame. `agents` yields (id, x, y, ori_x, ori_y) tuples."""
        assert self._con is not None, "writer not opened"
        cur = self._con.cursor()
        rows = [
            (frame, agent_id, x, y, ox, oy)
            for (agent_id, x, y, ox, oy) in agents
        ]
        if rows:
            cur.executemany(
                "INSERT INTO trajectory_data VALUES(?, ?, ?, ?, ?, ?)",
                rows,
            )
        # Each frame points at the (single) seeded geometry. The frame_data
        # table is what the v2+ readers consult for per-frame geometry.
        cur.execute(
            "INSERT INTO frame_data VALUES(?, ?)",
            (frame, self._geometry_hash),
        )
        self._buffered += 1
        if self._buffered >= self._commit_every:
            self._con.commit()
            self._buffered = 0

    def close(self) -> None:
        if self._con is None:
            return
        try:
            self._finalize_bounds_metadata()
            self._con.commit()
        finally:
            self._con.close()
            self._con = None

    def _create_schema(self) -> None:
        assert self._con is not None
        cur = self._con.cursor()
        cur.execute("BEGIN")
        cur.execute("DROP TABLE IF EXISTS trajectory_data")
        cur.execute(
            "CREATE TABLE trajectory_data ("
            "  frame INTEGER NOT NULL,"
            "  id INTEGER NOT NULL,"
            "  pos_x REAL NOT NULL,"
            "  pos_y REAL NOT NULL,"
            "  ori_x REAL NOT NULL,"
            "  ori_y REAL NOT NULL)"
        )
        cur.execute("CREATE INDEX frame_id_idx ON trajectory_data(frame, id)")

        cur.execute("DROP TABLE IF EXISTS metadata")
        cur.execute(
            "CREATE TABLE metadata(key TEXT NOT NULL UNIQUE PRIMARY KEY, value TEXT NOT NULL)"
        )
        cur.executemany(
            "INSERT INTO metadata VALUES(?, ?)",
            [("version", str(DATABASE_VERSION)), ("fps", str(self._fps))],
        )

        cur.execute("DROP TABLE IF EXISTS geometry")
        cur.execute(
            "CREATE TABLE geometry(hash INTEGER NOT NULL, wkt TEXT NOT NULL)"
        )
        cur.execute("CREATE UNIQUE INDEX geometry_hash on geometry(hash)")

        cur.execute("DROP TABLE IF EXISTS frame_data")
        cur.execute(
            "CREATE TABLE frame_data("
            "  frame INTEGER NOT NULL,"
            "  geometry_hash INTEGER NOT NULL)"
        )
        cur.execute("COMMIT")

    def _seed_geometry_and_levels(self) -> None:
        assert self._con is not None
        cur = self._con.cursor()
        cur.execute(
            "INSERT INTO geometry VALUES(?, ?)",
            (self._geometry_hash, self._geometry_wkt),
        )
        self._con.commit()

    def _finalize_bounds_metadata(self) -> None:
        """Compute geometry bounds from the WKT and write to metadata.

        The jupedsim writer updates xmin/xmax/ymin/ymax frame-by-frame to
        track geometry switches; with a single static geometry we can just
        compute once at close().
        """
        assert self._con is not None
        # Lazy import — keep module import cheap for tests that don't write.
        from shapely import from_wkt

        xmin, ymin, xmax, ymax = from_wkt(self._geometry_wkt).bounds
        self._xmin, self._xmax = xmin, xmax
        self._ymin, self._ymax = ymin, ymax
        cur = self._con.cursor()
        cur.executemany(
            "INSERT OR REPLACE INTO metadata(key, value) VALUES(?, ?)",
            [
                ("xmin", str(xmin)),
                ("xmax", str(xmax)),
                ("ymin", str(ymin)),
                ("ymax", str(ymax)),
            ],
        )
